name: Build and Push Image

on:
  push:
    tags:
      - v*
    branches:
      - main
      - feature-*

jobs:

  login-build-push:
    env:
        IMAGE_REGISTRY_GITHUB: ghcr.io/andrei-stepanov/ciboard-server
        IMAGE_REGISTRY_QUAY: quay.io/fedoraci/ciboard-server
        USER_QUAY: fedoraci+ciboard_github_ci
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:

    - name: Log in to the GitHub Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY_GITHUB }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY_QUAY }}
        username: ${{ env.USER_QUAY }}
        password: ${{ secrets.PASSWORD_QUAY }}

    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        tags: |
            ${{ env.IMAGE_REGISTRY_GITHUB }}:${{ github.sha }}
            ${{ ( env.BRANCH == 'main' && format('{0}:latest', env.IMAGE_REGISTRY_GITHUB) ) || '' }}
            ${{ env.IMAGE_REGISTRY_QUAY }}:${{ github.sha }}
            ${{ ( env.BRANCH == 'main' && format('{0}:latest', env.IMAGE_REGISTRY_QUAY) ) || '' }}
        containerfiles: |
          ./Dockerfile

    - name: Push to Repositories
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

# vim: noai:ts=2:sw=2 et
